# JVM args
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
# org.gradle.java.home=D\:/AndroidDev/jdk/jdk-17.0.19+10
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

android.useAndroidX=true
android.nonTransitiveRClass=true

kotlin.code.style=official
org.gradle.java.home=/home/galib/.gradle/jdks/jetbrains_s_r_o_-21-amd64-linux.2
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false
android.generateSyncIssueWhenLibraryConstraintsAreEnabled=false
